name: Ping RSSCloud

on:
    push:
        branches:
            - main

jobs:
    ping-rsscloud:
        runs-on: ubuntu-latest
        steps:
            - name: Ping RSSCloud
              run: |
                  curl -X POST "http://rpc.rsscloud.io:5337/pleaseNotify" \
                  -d "url=https://scotthanson.de/rss.xml" \
                  -d "port=80" \
                  -d "path=/rssCloudCallback"
